//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SALE_PRODUCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Cate
    {
        public long ID { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
        public int Sort { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public bool Status { get; set; }
    }
}
