//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCL_Voucher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        public long ID { get; set; }
        public string IMEI { get; set; }
    }
}
