//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCL_Voucher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traothuong
    {
        public long Id { get; set; }
        public Nullable<int> STT { get; set; }
        public string Phone { get; set; }
        public string Code { get; set; }
        public string Giai { get; set; }
        public string Noidung { get; set; }
    }
}
