//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCL_Voucher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string BuyAdr { get; set; }
        public string Province { get; set; }
        public string Product { get; set; }
        public string EMEI { get; set; }
        public string Model { get; set; }
        public string FileUpload { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    }
}
