//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string PhoneUse { get; set; }
        public string ChangePeople { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public Nullable<int> Cate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public string BuyAdr { get; set; }
        public string PRODUCT { get; set; }
        public string SERIAL { get; set; }
        public string MODEL { get; set; }
        public string IMEI { get; set; }
        public string INVOICE { get; set; }
        public string SIZE { get; set; }
        public string PAYMENT { get; set; }
        public string VOUCHER { get; set; }
        public string NVCH { get; set; }
        public bool TOPUP { get; set; }
    }
}
