//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer3004
    {
        public long ID { get; set; }
        public string Agent { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Activedate { get; set; }
        public string CusName { get; set; }
        public string Phone { get; set; }
        public string Size { get; set; }
        public string Model { get; set; }
        public string CMND { get; set; }
        public int Status { get; set; }
    }
}
