//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTopup
    {
        public long ID { get; set; }
        public Nullable<long> CusID { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Phone { get; set; }
        public string Provider { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Result { get; set; }
    }
}
