//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCLPromotionEntities : DbContext
    {
        public TCLPromotionEntities()
            : base("name=TCLPromotionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Brandname> Brandnames { get; set; }
        public virtual DbSet<KeyStore> KeyStores { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<VOUCHER_API> VOUCHER_API { get; set; }
        public virtual DbSet<MADUTHUONG> MADUTHUONGs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LogTopup> LogTopups { get; set; }
        public virtual DbSet<Customer3004> Customer3004 { get; set; }
        public virtual DbSet<Voucher3004> Voucher3004 { get; set; }
    }
}
