//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLPromotion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public long ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Activedate { get; set; }
        public string Activeby { get; set; }
        public string Sendby { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Usedate { get; set; }
        public string Cusname { get; set; }
        public string CCCD { get; set; }
        public string Usephone { get; set; }
        public string MODEL { get; set; }
        public string SIZE { get; set; }
        public string Agent { get; set; }
    }
}
